import streamlit as st
st.title("My First Streamlit App")
st.header("Welcome to my app!")
st.subheader("Features")
st.write("This is a simple Streamlit application.")
user_input = st.text_input("Enter your name:", "John Doe")
st.write("Hello, ", user_input)
user_bio=st.text_area("Enter your bio","I am a master Trainer")
st.write("Your bio:", user_bio)
user_age=st.number_input("Enter your age:", min_value=0, max_value=120, step=1)
st.write("Your age is:", user_age)
appointment_date=st.date_input("Select appointment date:")
st.write("Your appointment is scheduled for: ", appointment_date)
appointment_time=st.time_input("Select appointment time:")
st.write("Your appointment time is: ", appointment_time)
if st.button("Submit"):
    st.write("Name:", user_input)
    st.write("Bio:", user_bio)
    st.write("Age:", user_age)
    st.write("Appointment Date:", appointment_date)
    st.write("Appointment Time:", appointment_time)
